In [1]:
import os
import cv2
import numpy as np
from skimage.feature import hog
from sklearn.preprocessing import LabelEncoder
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import matplotlib.pyplot as plt

c:\Users\kanna\anaconda3\Lib\site-packages\paramiko\transport.py:219: CryptographyDeprecationWarning: Blowfish has been deprecated
  "class": algorithms.Blowfish,


In [2]:
data_dir = "D:\\PLANT_DISEASE\\archive (7)\\New Plant Diseases Dataset(Augmented)\\New Plant Diseases Dataset(Augmented)\\train_new" 

In [3]:
feature_vectors = []
labels = []

In [4]:
orientations = 9
pixels_per_cell = (8, 8)
cells_per_block = (2, 2)

In [5]:
for class_label in os.listdir(data_dir):
    class_dir = os.path.join(data_dir, class_label)
    
    if not os.path.isdir(class_dir):
        continue

    for image_file in os.listdir(class_dir):
        image_path = os.path.join(class_dir, image_file)
        
        image = cv2.imread(image_path)
        
        image = cv2.resize(image, (128, 128))
        
        image = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
        
        features = hog(image, orientations=orientations, pixels_per_cell=pixels_per_cell,
                       cells_per_block=cells_per_block, visualize=False, block_norm='L2-Hys')
        
        feature_vectors.append(features)
        labels.append(class_label)

In [6]:
feature_vectors

[array([0.2306182 , 0.13346892, 0.22842676, ..., 0.2008946 , 0.08372439,
        0.0774525 ]),
 array([0.30268497, 0.03407904, 0.10203084, ..., 0.13499041, 0.09386709,
        0.0188746 ]),
 array([0.24507741, 0.16712842, 0.09481246, ..., 0.21598185, 0.13302201,
        0.05906967]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0.26896884, 0.06819541, 0.06751796, ..., 0.12907258, 0.22681382,
        0.12307657]),
 array([0.12067994, 0.06029988, 0.02615877, ..., 0.10159426, 0.10573402,
        0.1693393 ]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0.14337981, 0.03607985, 0.14257316, ..., 0.19394747, 0.173526  ,
        0.15666971]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0.15013769, 0.18806132, 0.09449181, ..., 0.09926599, 0.10428593,
        0.05731488]),
 array([0.53333671, 0.02430443, 0.00851027, ..., 0.1360495 , 0.13725736,
        0.09420267]),
 array([0.16412188, 0.08704129, 0.08575131, ..., 0.06727034, 0.053802  ,
        0.09400519]),
 array([0.27051795, 0.081765

In [7]:
labels

['Apple___Black_rot',
 'Apple___Black_rot',
 'Apple___Black_rot',
 'Apple___Black_rot',
 'Apple___Black_rot',
 'Apple___Black_rot',
 'Apple___Black_rot',
 'Apple___Black_rot',
 'Apple___Black_rot',
 'Apple___Black_rot',
 'Apple___Black_rot',
 'Apple___Black_rot',
 'Apple___Black_rot',
 'Apple___Black_rot',
 'Apple___Black_rot',
 'Apple___Black_rot',
 'Apple___Black_rot',
 'Apple___Black_rot',
 'Apple___Black_rot',
 'Apple___Black_rot',
 'Apple___Black_rot',
 'Apple___Black_rot',
 'Apple___Black_rot',
 'Apple___Black_rot',
 'Apple___Black_rot',
 'Apple___Black_rot',
 'Apple___Black_rot',
 'Apple___Black_rot',
 'Apple___Black_rot',
 'Apple___Black_rot',
 'Apple___Black_rot',
 'Apple___Black_rot',
 'Apple___Black_rot',
 'Apple___Black_rot',
 'Apple___Black_rot',
 'Apple___Black_rot',
 'Apple___Black_rot',
 'Apple___Black_rot',
 'Apple___Black_rot',
 'Apple___Black_rot',
 'Apple___Black_rot',
 'Apple___Black_rot',
 'Apple___Black_rot',
 'Apple___Black_rot',
 'Apple___Black_rot',
 'Apple___

In [8]:
X = np.array(feature_vectors)
y = np.array(labels)

In [9]:
print(X)

[[0.2306182  0.13346892 0.22842676 ... 0.2008946  0.08372439 0.0774525 ]
 [0.30268497 0.03407904 0.10203084 ... 0.13499041 0.09386709 0.0188746 ]
 [0.24507741 0.16712842 0.09481246 ... 0.21598185 0.13302201 0.05906967]
 ...
 [0.22472384 0.17387665 0.06076164 ... 0.19280963 0.22150087 0.08089366]
 [0.13373838 0.23024784 0.04265059 ... 0.18660502 0.13951595 0.        ]
 [0.22160249 0.14613205 0.12106675 ... 0.07971506 0.12589608 0.18472035]]


In [10]:
label_encoder = LabelEncoder()
y = label_encoder.fit_transform(y)

In [11]:
y

array([ 0,  0,  0, ..., 13, 13, 13], dtype=int64)

In [12]:
dt_model = DecisionTreeClassifier(
    max_depth=100,  
    min_samples_split=2,  
    min_samples_leaf=1,  
    criterion="gini"  
)

In [13]:
dt_model.fit(X, y)

DecisionTreeClassifier(max_depth=100)

In [14]:
from joblib import dump

dump(dt_model, 'DT_PLANT_DISEASE.joblib')

['DT_PLANT_DISEASE.joblib']

In [18]:
data_valid_dir = "D:\\PLANT_DISEASE\\archive (7)\\New Plant Diseases Dataset(Augmented)\\New Plant Diseases Dataset(Augmented)\\valid" 

In [19]:
feature_vectors_valid = []
labels_valid = []

In [20]:
for class_label in os.listdir(data_valid_dir):
    class_dir = os.path.join(data_valid_dir, class_label)
    
    if not os.path.isdir(class_dir):
        continue

    for image_file in os.listdir(class_dir):
        image_path = os.path.join(class_dir, image_file)
        
        image = cv2.imread(image_path)
        
        image = cv2.resize(image, (128, 128))
        
        image = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
        
        features = hog(image, orientations=orientations, pixels_per_cell=pixels_per_cell,
                       cells_per_block=cells_per_block, visualize=False, block_norm='L2-Hys')
        
        feature_vectors_valid.append(features)
        labels_valid.append(class_label)

In [21]:
feature_vectors_valid

[array([0.34816679, 0.06535884, 0.10654796, ..., 0.10251548, 0.22643138,
        0.01894629]),
 array([0.09214594, 0.0208367 , 0.06185544, ..., 0.23477935, 0.23477935,
        0.08334843]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0.27978006, 0.19966136, 0.04151231, ..., 0.08809873, 0.00659001,
        0.01215138]),
 array([0.03634987, 0.01308605, 0.03428047, ..., 0.05214603, 0.0595694 ,
        0.06996123]),
 array([0.24888685, 0.        , 0.16550797, ..., 0.1428966 , 0.03633411,
        0.07208734]),
 array([0.10941622, 0.04539178, 0.04945058, ..., 0.02463803, 0.05494712,
        0.08989793]),
 array([0.21001855, 0.13413858, 0.10864896, ..., 0.00880275, 0.01254764,
        0.        ]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0.18999207, 0.14869231, 0.11485812, ..., 0.11457165, 0.16725454,
        0.04671482]),
 array([0.08919373, 0.10778661, 0.15164045, ..., 0.33038972, 0.10541883,
        0.20700377]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0.23189472, 0.160153

In [22]:
labels_valid

['Apple___Apple_scab',
 'Apple___Apple_scab',
 'Apple___Apple_scab',
 'Apple___Apple_scab',
 'Apple___Apple_scab',
 'Apple___Apple_scab',
 'Apple___Apple_scab',
 'Apple___Apple_scab',
 'Apple___Apple_scab',
 'Apple___Apple_scab',
 'Apple___Apple_scab',
 'Apple___Apple_scab',
 'Apple___Apple_scab',
 'Apple___Apple_scab',
 'Apple___Apple_scab',
 'Apple___Apple_scab',
 'Apple___Apple_scab',
 'Apple___Apple_scab',
 'Apple___Apple_scab',
 'Apple___Apple_scab',
 'Apple___Apple_scab',
 'Apple___Apple_scab',
 'Apple___Apple_scab',
 'Apple___Apple_scab',
 'Apple___Apple_scab',
 'Apple___Apple_scab',
 'Apple___Apple_scab',
 'Apple___Apple_scab',
 'Apple___Apple_scab',
 'Apple___Apple_scab',
 'Apple___Apple_scab',
 'Apple___Apple_scab',
 'Apple___Apple_scab',
 'Apple___Apple_scab',
 'Apple___Apple_scab',
 'Apple___Apple_scab',
 'Apple___Apple_scab',
 'Apple___Apple_scab',
 'Apple___Apple_scab',
 'Apple___Apple_scab',
 'Apple___Apple_scab',
 'Apple___Apple_scab',
 'Apple___Apple_scab',
 'Apple___A

In [23]:
X_valid = np.array(feature_vectors_valid)
y_valid = np.array(labels_valid)

In [24]:
label_encoder = LabelEncoder()
y_valid = label_encoder.fit_transform(y_valid)

In [28]:
y_valid_pred = dt_model.predict(X_valid)
accuracy_valid = accuracy_score(y_valid, y_valid_pred)
conf_matrix_valid = confusion_matrix(y_valid, y_valid_pred)
class_report_valid = classification_report(y_valid, y_valid, zero_division=1)

In [29]:
accuracy_valid

0.17300250398361028

In [15]:
class_dir_test = "D:\\PLANT_DISEASE\\archive (7)\\test\\test"

In [16]:
feature_test=[]
label_test=[]

In [17]:
for image_file in os.listdir(class_dir_test):
    image_path = os.path.join(class_dir_test, image_file)
    
    image = cv2.imread(image_path)
    
    image = cv2.resize(image, (128, 128))
    
    image = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
    
    features = hog(image, orientations=orientations, pixels_per_cell=pixels_per_cell,
                    cells_per_block=cells_per_block, visualize=False, block_norm='L2-Hys')
    
    feature_test.append(features)
    label_test.append(image_file)

In [18]:
feature_test

[array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0.38116011, 0.        , 0.        , ..., 0.2942634 , 0.2942634 ,
        0.2942634 ]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0.34665116, 0.2475154 , 0.        , ..., 0.06811334, 0.09349503,
        0.14697103]),
 array([0.23211236, 0.10355923, 0.2093943 , ..., 0.0656748 , 0.10546845,
        0.17560894]),
 array([0.22322379, 0.04099078, 0.22322379, ..., 0.07418761, 0.17334201,
        0.10564924]),
 array([0.17994736, 0.01252602, 0.11606579, ..., 0.09627995, 0.13474027,
        0.06011489]),
 array([0.25400885, 0.17894684, 0.07648204, ..., 0.04692329, 0.15721423,
        0.07063243]),
 array([0.18032431, 0.0812374 , 0.03820471, ..., 0.15355383, 0.19682117,
        0.04734452]),
 array([0.08884694, 0.05555651, 0.10346159, ..., 0.04606894, 0.09437805,
        0.08384287]),
 array([0.22676064, 0.07214973, 0.15854789, ..., 0.07099724, 0.03806391,
        0.04822658]),
 array([0.20631424, 0.108188

In [19]:
label_test

['Apple___Black_rot.JPG',
 'Corn_(maize)___Common_rust_ (1).JPG',
 'Corn_(maize)___Common_rust_ (2).JPG',
 'Corn_(maize)___Common_rust_ (3).JPG',
 'Corn_(maize)___Common_rust_.JPG',
 'Grape___Black_rot.JPG',
 'Orange___Haunglongbing_(Citrus_greening).JPG',
 'Peach___Bacterial_spot.JPG',
 'PotatoEarlyBlight1.JPG',
 'PotatoEarlyBlight2.JPG',
 'PotatoEarlyBlight3.JPG',
 'PotatoEarlyBlight4.JPG',
 'PotatoEarlyBlight5.JPG',
 'Potato___Early_blight.JPG',
 'Squash___Powdery_mildew.JPG',
 'Strawberry___Leaf_scorch.JPG',
 'Tomato___Tomato_Yellow_Leaf_Curl_Virus (1).JPG',
 'Tomato___Tomato_Yellow_Leaf_Curl_Virus (2).JPG',
 'Tomato___Tomato_Yellow_Leaf_Curl_Virus (3).JPG',
 'Tomato___Tomato_Yellow_Leaf_Curl_Virus (4).JPG',
 'Tomato___Tomato_Yellow_Leaf_Curl_Virus (5).JPG',
 'Tomato___Tomato_Yellow_Leaf_Curl_Virus (6).JPG',
 'Tomato___Tomato_Yellow_Leaf_Curl_Virus.JPG']

In [20]:
x_test =np.array(feature_test)
y_test = np.array([0,3,3,3,3,4,5,6,8,8,8,8,8,8,11,12,13,13,13,13,13,13,13])

In [21]:
y_test_pred = dt_model.predict(x_test)
accuracy_test = accuracy_score(y_test, y_test_pred)
conf_matrix_valid = confusion_matrix(y_test, y_test_pred)
class_report_valid = classification_report(y_test, y_test_pred, zero_division=1)

In [22]:
y_test_pred

array([ 0,  3,  3,  3,  3,  4,  5,  6, 13, 11, 10,  5, 10,  8, 11, 12, 11,
       13,  4, 13, 13,  2, 13], dtype=int64)

In [23]:
accuracy_test

0.6521739130434783