In [1]:
import os
import cv2
import numpy as np
from skimage.feature import hog
from sklearn.preprocessing import LabelEncoder
import xgboost as xgb
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import matplotlib.pyplot as plt

c:\Users\kanna\anaconda3\Lib\site-packages\paramiko\transport.py:219: CryptographyDeprecationWarning: Blowfish has been deprecated
  "class": algorithms.Blowfish,


In [2]:
data_dir = "D:\\PLANT_DISEASE\\archive (7)\\New Plant Diseases Dataset(Augmented)\\New Plant Diseases Dataset(Augmented)\\train" 

In [3]:
feature_vectors = []
labels = []

In [4]:
orientations = 9
pixels_per_cell = (8, 8)
cells_per_block = (2, 2)

In [5]:
for class_label in os.listdir(data_dir):
    class_dir = os.path.join(data_dir, class_label)
    
    if not os.path.isdir(class_dir):
        continue

    for image_file in os.listdir(class_dir):
        image_path = os.path.join(class_dir, image_file)
        
        image = cv2.imread(image_path)
        
        image = cv2.resize(image, (128, 128))
        
        image = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
        
        features = hog(image, orientations=orientations, pixels_per_cell=pixels_per_cell,
                       cells_per_block=cells_per_block, visualize=False, block_norm='L2-Hys')
        
        feature_vectors.append(features)
        labels.append(class_label)

In [6]:
feature_vectors

[array([0.24970511, 0.04026191, 0.12829244, ..., 0.07112913, 0.06919671,
        0.04170013]),
 array([0.22603369, 0.22280133, 0.17229731, ..., 0.06889997, 0.16817242,
        0.12376413]),
 array([0.27046337, 0.112848  , 0.        , ..., 0.1138454 , 0.11448549,
        0.07271001]),
 array([0.07588027, 0.03994336, 0.03472736, ..., 0.02097628, 0.11723413,
        0.27528611]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0.19228689, 0.01846508, 0.18159251, ..., 0.13935816, 0.08434227,
        0.04955039]),
 array([0.09947699, 0.02228127, 0.08821611, ..., 0.21056496, 0.27341773,
        0.13406568]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0.22668912, 0.02647867, 0.22668912, ..., 0.0750184 , 0.11754991,
        0.19341278]),
 array([0.28653903, 0.01510647, 0.04777085, ..., 0.02159907, 0.01868191,
        0.00834887]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0.28044991, 0.28044991, 0.28044991, ..., 0.10366192, 0.05463463,
        0.15453006]),
 array([0., 0., 0., ..., 0.,

In [7]:
labels

['Apple___Apple_scab',
 'Apple___Apple_scab',
 'Apple___Apple_scab',
 'Apple___Apple_scab',
 'Apple___Apple_scab',
 'Apple___Apple_scab',
 'Apple___Apple_scab',
 'Apple___Apple_scab',
 'Apple___Apple_scab',
 'Apple___Apple_scab',
 'Apple___Apple_scab',
 'Apple___Apple_scab',
 'Apple___Apple_scab',
 'Apple___Apple_scab',
 'Apple___Apple_scab',
 'Apple___Apple_scab',
 'Apple___Apple_scab',
 'Apple___Apple_scab',
 'Apple___Apple_scab',
 'Apple___Apple_scab',
 'Apple___Apple_scab',
 'Apple___Apple_scab',
 'Apple___Apple_scab',
 'Apple___Apple_scab',
 'Apple___Apple_scab',
 'Apple___Apple_scab',
 'Apple___Apple_scab',
 'Apple___Apple_scab',
 'Apple___Apple_scab',
 'Apple___Apple_scab',
 'Apple___Apple_scab',
 'Apple___Apple_scab',
 'Apple___Apple_scab',
 'Apple___Apple_scab',
 'Apple___Apple_scab',
 'Apple___Apple_scab',
 'Apple___Apple_scab',
 'Apple___Apple_scab',
 'Apple___Apple_scab',
 'Apple___Apple_scab',
 'Apple___Apple_scab',
 'Apple___Apple_scab',
 'Apple___Apple_scab',
 'Apple___A

In [8]:
X = np.array(feature_vectors)

In [9]:
y = np.array(labels)

In [41]:
print(X)

[[0.24970511 0.04026191 0.12829244 ... 0.07112913 0.06919671 0.04170013]
 [0.22603369 0.22280133 0.17229731 ... 0.06889997 0.16817242 0.12376413]
 [0.27046337 0.112848   0.         ... 0.1138454  0.11448549 0.07271001]
 ...
 [0.2450041  0.12717484 0.2450041  ... 0.04888984 0.         0.01762973]
 [0.22867408 0.22867408 0.12574024 ... 0.13969565 0.10657399 0.05548487]
 [0.10591976 0.05455702 0.02139902 ... 0.07014982 0.04547306 0.09099296]]


In [15]:
label_encoder = LabelEncoder()
y = label_encoder.fit_transform(y)

In [16]:
y

array([ 0,  0,  0, ..., 35, 35, 35], dtype=int64)

In [17]:
xgboost_model = xgb.XGBClassifier(
    learning_rate=0.1,
    n_estimators=100,
    objective='multi:softmax',  # For multi-class classification
    num_class=len(label_encoder.classes_)  # Number of classes
)

In [18]:
xgboost_model.fit(X,y)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.1, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=100, n_jobs=None, num_class=38,
              num_parallel_tree=None, ...)

In [31]:
class_dir_test = "D:\\PLANT_DISEASE\\archive (7)\\test\\test_final"

In [32]:
feature_test=[]
label_test=[]

In [33]:
for image_file in os.listdir(class_dir_test):
    image_path = os.path.join(class_dir_test, image_file)
    
    image = cv2.imread(image_path)
    
    image = cv2.resize(image, (128, 128))
    
    image = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
    
    features = hog(image, orientations=orientations, pixels_per_cell=pixels_per_cell,
                    cells_per_block=cells_per_block, visualize=False, block_norm='L2-Hys')
    
    feature_test.append(features)
    label_test.append(image_file)

In [34]:
feature_test

[array([0.3878978 , 0.04213401, 0.02896267, ..., 0.09204177, 0.08195669,
        0.08477164]),
 array([0.17569234, 0.06930438, 0.14314371, ..., 0.        , 0.21528088,
        0.0906029 ]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0.38116011, 0.        , 0.        , ..., 0.2942634 , 0.2942634 ,
        0.2942634 ]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0.34665116, 0.2475154 , 0.        , ..., 0.06811334, 0.09349503,
        0.14697103]),
 array([0.21679891, 0.05887299, 0.12048961, ..., 0.10753159, 0.04857285,
        0.        ]),
 array([0.20518527, 0.15536076, 0.13425269, ..., 0.12229223, 0.13323229,
        0.11584329]),
 array([0.23169404, 0.05120109, 0.09467042, ..., 0.18466962, 0.11242249,
        0.2215013 ]),
 array([0.23211236, 0.10355923, 0.2093943 , ..., 0.0656748 , 0.10546845,
        0.17560894]),
 array([0.20376697, 0.11517297, 0.1362592 , ..., 0.12960245, 0.07519557,
        0.0

In [37]:
x_test =np.array(feature_test)
y_test = np.array([0,0,0,0,3,3,3,3,4,4,4,4,5,5,5,5,6,6,6,6,8,8,8,8,11,12,12,12,14,14,14,14])


In [38]:
y_test_pred = xgboost_model.predict(x_test)
accuracy_test = accuracy_score(y_test, y_test_pred)
conf_matrix_valid = confusion_matrix(y_test, y_test_pred)
class_report_valid = classification_report(y_test, y_test_pred, zero_division=1)

In [44]:
acuracy_test

0.463